---
- name: "{{ role_name }} | {{ task.name }} | Ensure useful packages are installed"
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
...
